# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    assignees: [ "marko-bekhta" ]
  - package-ecosystem: "maven"
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
      day: "tuesday"
    assignees: [ "marko-bekhta" ]
    open-pull-requests-limit: 20
    groups:
      # This group combines all build-only dependencies. Published artifacts do not depend on them.
      # Grouping such dependencies will make Dependabot create PRs with a branch name
      # following the pattern (`dependabot/maven/build-dependencies-.*`)
      # and with a title like `Bump the build-dependencies group with 8 updates` that we can easily
      # use for Hibernate Bot rules.
      build-dependencies:
        patterns:
          # Maven extensions:
          - "*-maven-extension"
          - "org.hibernate.infra.develocity:*"
          # Maven plugins:
          - "*maven*plugin*"
          - "org.apache.maven*:*"
          - "*surefire*"
          - "*forbiddenapis*"
          - "com.puppycrawl.tools:*"
          # Other test/build dependencies
          - "org.apache.groovy:groovy-jsr223"
          - "org.openjdk.jmh:*" # performance testing dependency
          - "com.google.guava:guava" # Guava is used in our test utils
          - "org.asciidoctor:*" # Asciidoctor is used for rendering the documentation
          - "org.apache.logging.log4j:*"
          - "org.slf4j:*"
          - "org.ow2.asm:*" # for Surefire/Failsafe plugins to support builds on latest JDKs
          - "junit:*"
          - "org.testng:*"
          - "org.easymock:*"
          - "org.jboss.arquillian:*"
          - "org.jboss.arquillian.container:*"
          - "org.jboss.modules:*"
          - "org.jboss.shrinkwrap.resolver:*"
          - "com.fasterxml.woodstox:*"
          - "io.rest-assured:*"
          - "net.bytebuddy:*"
          - "com.fasterxml.jackson.core:*"
          - "org.springframework:*"
          # only used for perf tests based on javax:
          - "org.glassfish:javax.el"
          - "org.codehaus.plexus:plexus-utils"
    ignore:
      - dependency-name: "javax.validation:*"
      - dependency-name: "org.apache.bval:*"
      # dependencies that we align on Wildfly version that is used:
      - dependency-name: "org.jboss.weld:*"
      - dependency-name: "org.wildfly.arquillian:*"
      - dependency-name: "jakarta.validation:jakarta.validation-api"
      - dependency-name: "jakarta.persistence:jakarta.persistence-api"
      - dependency-name: "jakarta.el:jakarta.el-api"
        # We are managing the version of AssertJ manually:
        #    - tck-runner requires a specific version of AssertJ aligned with the Jakarta Validation TCK
        #    - all other modules are using a more recent version (latest)
        #  we cannot enable the automatic updates as those will constantly push us to change the version in the TCK module
      - dependency-name: "org.assertj:*"
        # We have a fixed major version of OpenJFX to work with the min JDK we require
      - dependency-name: "org.openjfx:*"
        update-types:
          - version-update:semver-major
          - version-update:semver-minor
